// Code generated by ormgen; DO NOT EDIT.
package model

import (
	"database/sql"

	"github.com/mickamy/ormgen/orm"
)

// Users returns a new Query for the users table.
func Users(db orm.Querier) *orm.Query[User] {
	return orm.NewQuery[User](
		db, "users", usersColumns, "id",
		scanUser, userColumnValuePairs, setUserPK,
	)
}

var usersColumns = []string{"id", "name", "email", "created_at"}

func scanUser(rows *sql.Rows) (User, error) {
	cols, _ := rows.Columns()
	var v User
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "name":
			dest[i] = &v.Name
		case "email":
			dest[i] = &v.Email
		case "created_at":
			dest[i] = &v.CreatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func userColumnValuePairs(v *User, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "name", "email", "created_at"},
			[]any{v.ID, v.Name, v.Email, v.CreatedAt}
	}
	return []string{"name", "email", "created_at"},
		[]any{v.Name, v.Email, v.CreatedAt}
}

func setUserPK(v *User, id int64) {
	v.ID = int(id)
}
