// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"context"
	"database/sql"

	"github.com/mickamy/ormgen/example/model"
	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/ormgen/scope"
)

// Posts returns a new Query for the posts table.
func Posts(db orm.Querier) *orm.Query[model.Post] {
	q := orm.NewQuery[model.Post](
		db, "posts", postsColumns, "id",
		scanPost, postColumnValuePairs, setPostPK,
	)
	q.RegisterJoin("User", orm.JoinConfig{
		TargetTable: "users", TargetColumn: "id",
		SourceTable: "posts", SourceColumn: "user_id",
	})
	q.RegisterPreloader("User", preloadPostUser)
	return q
}

var postsColumns = []string{"id", "user_id", "title", "body"}

func scanPost(rows *sql.Rows) (model.Post, error) {
	cols, _ := rows.Columns()
	var v model.Post
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "user_id":
			dest[i] = &v.UserID
		case "title":
			dest[i] = &v.Title
		case "body":
			dest[i] = &v.Body
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func postColumnValuePairs(v *model.Post, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "user_id", "title", "body"},
			[]any{v.ID, v.UserID, v.Title, v.Body}
	}
	return []string{"user_id", "title", "body"},
		[]any{v.UserID, v.Title, v.Body}
}

func setPostPK(v *model.Post, id int64) {
	v.ID = int(id)
}

func preloadPostUser(ctx context.Context, db orm.Querier, results []model.Post) error {
	if len(results) == 0 {
		return nil
	}
	ids := make([]int, len(results))
	for i := range results {
		ids[i] = results[i].UserID
	}
	related, err := Users(db).Scopes(scope.In("id", ids)).All(ctx)
	if err != nil {
		return err
	}
	byPK := make(map[int]*model.User)
	for i := range related {
		byPK[related[i].ID] = &related[i]
	}
	for i := range results {
		results[i].User = byPK[results[i].UserID]
	}
	return nil
}
