// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"

	"github.com/mickamy/ormgen/example/model"
	"github.com/mickamy/ormgen/orm"
)

// Profiles returns a new Query for the profiles table.
func Profiles(db orm.Querier) *orm.Query[model.Profile] {
	return orm.NewQuery[model.Profile](
		db, "profiles", profilesColumns, "id",
		scanProfile, profileColumnValuePairs, setProfilePK,
	)
}

var profilesColumns = []string{"id", "user_id", "bio"}

func scanProfile(rows *sql.Rows) (model.Profile, error) {
	cols, _ := rows.Columns()
	var v model.Profile
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "user_id":
			dest[i] = &v.UserID
		case "bio":
			dest[i] = &v.Bio
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func profileColumnValuePairs(v *model.Profile, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "user_id", "bio"},
			[]any{v.ID, v.UserID, v.Bio}
	}
	return []string{"user_id", "bio"},
		[]any{v.UserID, v.Bio}
}

func setProfilePK(v *model.Profile, id int64) {
	v.ID = int(id)
}
