// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"database/sql"

	"github.com/mickamy/ormgen/example/model"
	"github.com/mickamy/ormgen/orm"
)

// Tags returns a new Query for the tags table.
func Tags(db orm.Querier) *orm.Query[model.Tag] {
	return orm.NewQuery[model.Tag](
		db, orm.ResolveTableName[model.Tag]("tags"), tagsColumns, "id",
		scanTag, tagColumnValuePairs, setTagPK,
	)
}

var tagsColumns = []string{"id", "name"}

func scanTag(rows *sql.Rows) (model.Tag, error) {
	cols, _ := rows.Columns()
	var v model.Tag
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "name":
			dest[i] = &v.Name
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func tagColumnValuePairs(v *model.Tag, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "name"},
			[]any{v.ID, v.Name}
	}
	return []string{"name"},
		[]any{v.Name}
}

func setTagPK(v *model.Tag, id int64) {
	v.ID = int(id)
}
