// Code generated by ormgen; DO NOT EDIT.
package query

import (
	"context"
	"database/sql"

	"github.com/mickamy/ormgen/example/model"
	"github.com/mickamy/ormgen/orm"
	"github.com/mickamy/ormgen/scope"
)

// Users returns a new Query for the users table.
func Users(db orm.Querier) *orm.Query[model.User] {
	q := orm.NewQuery[model.User](
		db, "users", usersColumns, "id",
		scanUser, userColumnValuePairs, setUserPK,
	)
	q.RegisterJoin("Posts", orm.JoinConfig{
		TargetTable: "posts", TargetColumn: "user_id",
		SourceTable: "users", SourceColumn: "id",
	})
	q.RegisterPreloader("Posts", preloadUserPosts)
	q.RegisterJoin("Profile", orm.JoinConfig{
		TargetTable: "profiles", TargetColumn: "user_id",
		SourceTable: "users", SourceColumn: "id",
	})
	q.RegisterPreloader("Profile", preloadUserProfile)
	return q
}

var usersColumns = []string{"id", "name", "email", "created_at"}

func scanUser(rows *sql.Rows) (model.User, error) {
	cols, _ := rows.Columns()
	var v model.User
	dest := make([]any, len(cols))
	for i, col := range cols {
		switch col {
		case "id":
			dest[i] = &v.ID
		case "name":
			dest[i] = &v.Name
		case "email":
			dest[i] = &v.Email
		case "created_at":
			dest[i] = &v.CreatedAt
		default:
			dest[i] = new(any)
		}
	}
	err := rows.Scan(dest...)
	return v, err
}

func userColumnValuePairs(v *model.User, includesPK bool) ([]string, []any) {
	if includesPK {
		return []string{"id", "name", "email", "created_at"},
			[]any{v.ID, v.Name, v.Email, v.CreatedAt}
	}
	return []string{"name", "email", "created_at"},
		[]any{v.Name, v.Email, v.CreatedAt}
}

func setUserPK(v *model.User, id int64) {
	v.ID = int(id)
}

func preloadUserPosts(ctx context.Context, db orm.Querier, results []model.User) error {
	if len(results) == 0 {
		return nil
	}
	ids := make([]int, len(results))
	for i := range results {
		ids[i] = results[i].ID
	}
	related, err := Posts(db).Scopes(scope.In("user_id", ids)).All(ctx)
	if err != nil {
		return err
	}
	byFK := make(map[int][]model.Post)
	for _, r := range related {
		byFK[r.UserID] = append(byFK[r.UserID], r)
	}
	for i := range results {
		results[i].Posts = byFK[results[i].ID]
	}
	return nil
}
func preloadUserProfile(ctx context.Context, db orm.Querier, results []model.User) error {
	if len(results) == 0 {
		return nil
	}
	ids := make([]int, len(results))
	for i := range results {
		ids[i] = results[i].ID
	}
	related, err := Profiles(db).Scopes(scope.In("user_id", ids)).All(ctx)
	if err != nil {
		return err
	}
	byFK := make(map[int]*model.Profile)
	for i := range related {
		byFK[related[i].UserID] = &related[i]
	}
	for i := range results {
		results[i].Profile = byFK[results[i].ID]
	}
	return nil
}
